# Generated by Django 2.2.1 on 2019-05-22 19:12

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.FileField(default='static/images/noprofile.png', upload_to='static/images/service-provider/')),
                ('expect', models.TextField(help_text='Short description for the profile', max_length=368)),
                ('description', models.TextField(help_text='Profile description. use col in your HMTL tag to create column')),
                ('slug', models.SlugField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('background_image', models.FileField(default='static/images/defaultbg.jpg', upload_to='static/images/%Y')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_provider.ServiceProvider')),
            ],
        ),
    ]
