# Generated by Django 2.2.1 on 2019-05-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='ceo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
