# Generated by Django 2.2.1 on 2019-05-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0002_auto_20190523_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
