# Generated by Django 2.2.1 on 2019-05-23 17:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0003_auto_20190523_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Profile description. use col in your HMTL tag to create column'),
        ),
    ]
