# Generated by Django 2.2.1 on 2019-05-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changemakers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changemaker',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='changemaker',
            name='expect',
            field=models.TextField(blank=True, help_text='Insert expect text'),
        ),
    ]
