# Generated by Django 2.2.1 on 2019-05-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changemakers', '0002_auto_20190521_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changemaker',
            name='image_url',
            field=models.FileField(default='static/images/noprofile.png', upload_to='static/images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='changemaker',
            name='organisation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
