# Generated by Django 2.2.1 on 2019-06-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changemakers', '0003_auto_20190522_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changemaker',
            name='image_url',
            field=models.FileField(default='static/images/noprofile.png', upload_to=''),
        ),
    ]
