# Generated by Django 2.2.1 on 2019-05-21 15:41

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Organisation name', max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('email', models.EmailField(help_text='Organisation Email', max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('logo', models.FileField(default='static/images/noprofile.png', upload_to='media/static/images/%Y/%m/%d', verbose_name='Profile logo')),
                ('expect', models.TextField(blank=True, help_text='Expect text', max_length=255)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabs', models.CharField(default='', help_text='Please name your tabs by separating them by a ,', max_length=255)),
                ('about_us', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('service_or_program', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('support', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('contact_us', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('Website', models.URLField(blank=True, verbose_name='Website')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngo_npo_profile.Organisation', verbose_name='organisation')),
            ],
            options={
                'verbose_name': 'Organisation Profile',
            },
        ),
    ]
