# Generated by Django 2.2.1 on 2019-05-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_npo_profile', '0002_auto_20190521_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='background_image',
            field=models.FileField(default='static/images/defaultbg.jpg', upload_to='static/images/%Y'),
        ),
    ]
