# Generated by Django 2.2.1 on 2019-05-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_npo_profile', '0003_organisation_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='ceo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='email',
            field=models.EmailField(blank=True, help_text='Organisation Email', max_length=254),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
