# Generated by Django 2.2.1 on 2019-05-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_npo_profile', '0005_auto_20190523_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='website_url',
            field=models.URLField(blank=True, help_text='website Address'),
        ),
    ]
