# Generated by Django 2.2.1 on 2019-05-28 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_npo_profile', '0006_organisation_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='background_image',
            field=models.FileField(default='static/images/defaultbg.jpg', upload_to='ngo-npo/'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=models.FileField(default='static/images/noprofile.png', upload_to='ngo-npo/', verbose_name='Profile logo'),
        ),
    ]
