# Generated by Django 2.2.1 on 2019-05-21 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ngo_or_npo',
            field=models.ForeignKey(blank=True, help_text='please assign post to NGO or NPO', null=True, on_delete=django.db.models.deletion.CASCADE, to='ngo_npo_profile.Organisation'),
        ),
    ]
