# Generated by Django 2.2.1 on 2019-05-21 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20190521_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Assign post to Company', null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
    ]
