# Generated by Django 2.2.1 on 2019-05-23 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0001_initial'),
        ('mainsite', '0005_auto_20190522_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='service_provider',
            field=models.ForeignKey(blank=True, help_text='Assign post to Service Provider', null=True, on_delete=django.db.models.deletion.CASCADE, to='service_provider.ServiceProvider'),
        ),
    ]
