# Generated by Django 2.2.1 on 2019-05-23 17:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0004_auto_20190523_1753'),
        ('mainsite', '0006_post_service_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='service_provider',
            field=models.ForeignKey(blank=True, help_text='Assign post to Service Provider', null=True, on_delete=django.db.models.deletion.CASCADE, to='service_provider.ServiceProvider'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='service_provider',
            field=models.ForeignKey(blank=True, help_text='Assign post to Service Provider', null=True, on_delete=django.db.models.deletion.CASCADE, to='service_provider.ServiceProvider'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='organisation_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
