# Generated by Django 2.2.1 on 2019-05-23 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20190523_0839'),
        ('service_provider', '0004_auto_20190523_1753'),
        ('ngo_npo_profile', '0005_auto_20190523_0840'),
        ('mainsite', '0007_auto_20190523_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Assign post to Company', null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='videopost',
            name='ngo_or_npo',
            field=models.ForeignKey(blank=True, help_text='please assign post to NGO or NPO', null=True, on_delete=django.db.models.deletion.CASCADE, to='ngo_npo_profile.Organisation'),
        ),
        migrations.AddField(
            model_name='videopost',
            name='service_provider',
            field=models.ForeignKey(blank=True, help_text='Assign post to Service Provider', null=True, on_delete=django.db.models.deletion.CASCADE, to='service_provider.ServiceProvider'),
        ),
    ]
