# Generated by Django 2.2.1 on 2019-05-23 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_auto_20190523_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopost',
            name='slug',
        ),
    ]
