# Generated by Django 2.2.1 on 2019-05-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_remove_videopost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
