# Generated by Django 2.2.1 on 2019-05-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_videopost_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='title',
            field=models.CharField(blank=True, help_text='Video title', max_length=100),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='video_url',
            field=models.URLField(blank=True, help_text='example: http://www.youtube/myvideourl'),
        ),
    ]
