# Generated by Django 2.2.1 on 2019-05-28 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_website_url'),
        ('ngo_npo_profile', '0007_auto_20190528_1849'),
        ('service_provider', '0005_serviceprovider_website_url'),
        ('mainsite', '0013_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='company_logo',
            field=models.FileField(default='/static/images/wecanchangeopportunity.jpg', upload_to='opportunities/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.FileField(default='static/images/postnoimage.png', upload_to='post/'),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activate', models.CharField(choices=[('active', 'Active'), ('deactivate', 'Deactivate')], default='deactivate', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('ngo_npo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngo_npo_profile.Organisation')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_provider.ServiceProvider')),
            ],
        ),
    ]
