# Generated by Django 2.2.1 on 2019-05-29 09:01

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_npo_profile', '0007_auto_20190528_1849'),
        ('companies', '0005_company_website_url'),
        ('service_provider', '0005_serviceprovider_website_url'),
        ('mainsite', '0014_auto_20190528_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('send', 'Send')], max_length=10)),
                ('date_to_be_sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(help_text='Select to assign this newsletter', on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('organisation', models.ForeignKey(help_text='Select to assign this newsletter', on_delete=django.db.models.deletion.CASCADE, to='ngo_npo_profile.Organisation')),
                ('service_provider', models.ForeignKey(help_text='Select to assign this newsletter', on_delete=django.db.models.deletion.CASCADE, to='service_provider.ServiceProvider')),
            ],
        ),
    ]
