# Generated by Django 2.2.1 on 2019-05-29 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0015_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Select to assign this newsletter', null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text='Select to assign this newsletter', null=True, on_delete=django.db.models.deletion.CASCADE, to='ngo_npo_profile.Organisation'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='service_provider',
            field=models.ForeignKey(blank=True, help_text='Select to assign this newsletter', null=True, on_delete=django.db.models.deletion.CASCADE, to='service_provider.ServiceProvider'),
        ),
    ]
