# Generated by Django 2.2.1 on 2019-06-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0016_auto_20190529_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_main_guest',
            field=models.FileField(default='static/images/noprofile.png', upload_to='events/'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_main_guest_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
