# Generated by Django 2.2.1 on 2019-05-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ceo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, help_text='Company Email', max_length=254),
        ),
    ]
